import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CallbackWidget from '../components/CallbackWidget';
import HospifyChatbot from '../components/HospifyChatbot';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HOSPIFY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        {children}
        <CallbackWidget />
        <HospifyChatbot />
      </body>
    </html>
  );
}
